#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="BackLog"
#EXEC="python2.6 /usr/lib/python2.6/backlog/BackLogMain.py"
EXEC="python3.1 /usr/lib/python3.1/backlog/BackLogMain.py"

SUBPROCESSFAKENAME=subprocessfaked
SUBPROCESSFAKED=/usr/bin/subprocessfaked
STARTSTOPDAEMON=/sbin/start-stop-daemon


case "$1" in
  start)
    echo -n "Starting $DESC... "
    if [ -x $SUBPROCESSFAKED ]; then
    	echo -n "and $SUBPROCESSFAKENAME... "
		$SUBPROCESSFAKED | logger -t $SUBPROCESSFAKENAME &
	fi
    screen -S backlog -d -m $EXEC
    echo "done."
    ;;
  stop)
    echo -n "Stopping $DESC... "
    PID=`pgrep -f -x "$EXEC"`
    if [ $? = 0 ]; then
        kill -INT $PID
		wait $PID
	fi
    if [ -x $SUBPROCESSFAKED ]; then
    	echo -n "and $SUBPROCESSFAKENAME... "
		killall $SUBPROCESSFAKENAME
    fi
    echo "done."
    ;;
#  restart)
#    echo -n "Restarting $DESC... "
#    PID=`pgrep -f -x "$EXEC"`
#    if [ -x $SUBPROCESSFAKED ]; then
#    	echo -n "and $SUBPROCESSFAKENAME... "
#		killall $SUBPROCESSFAKENAME
#    fi
#    if [ $? = 0 ]; then
#        kill -INT $PID
#        wait $PID
#	fi
#    if [ -x $SUBPROCESSFAKED ]; then
#		$SUBPROCESSFAKED | logger -t $SUBPROCESSFAKENAME &
#	fi
#    screen -S backlog -d -m $EXEC
#    echo "done."
#    ;;
  *)
    echo "Usage: /etc/init.d/backlog {start|stop}" #|restart}"
    ;;
esac
