#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="BackLog"
EXEC="python2.6 /usr/lib/python2.6/backlog/BackLogMain.py"
#EXEC="python3.1 /usr/lib/python3.1/backlog/BackLogMain.py"

SUBPROCESSFAKENAME=subprocessfaked
SUBPROCESSFAKED=/usr/bin/subprocessfaked
STARTSTOPDAEMON=/sbin/start-stop-daemon


case "$1" in
  start)
    echo -n "Starting $DESC... "
    if [ -x $SUBPROCESSFAKED ]; then
    	echo -n "and $SUBPROCESSFAKENAME... "
		$SUBPROCESSFAKED | logger -t $SUBPROCESSFAKENAME &
	fi
    screen -S backlog -d -m $EXEC
    echo "done."
    ;;
  stop)
    echo -n "Stopping $DESC... "
    PID=`pgrep -f -x "$EXEC"`
    if [ $? = 0 ]; then
        kill -INT $PID
        while ps -p $PID > /dev/null; do sleep 1; done
	fi
    if [ -x $SUBPROCESSFAKED ]; then
    	echo -n "and $SUBPROCESSFAKENAME... "
		pkill -TERM -P $(pgrep -o $SUBPROCESSFAKENAME)
    fi
    echo "done."
    ;;
  restart)
    echo -n "Restarting $DESC... waiting for $DESC to shutdown... "
    PID=`pgrep -f -x "$EXEC"`
    if [ $? = 0 ]; then
        kill -INT $PID
        while ps -p $PID > /dev/null; do sleep 1; done
	fi
    echo -n "restarting $SUBPROCESSFAKENAME... "
    if [ -x $SUBPROCESSFAKED ]; then
    	PID=`pgrep -o $SUBPROCESSFAKENAME`
		pkill -TERM -P $PID
		while ps -p $PID > /dev/null; do sleep 1; done
		$SUBPROCESSFAKED | logger -t $SUBPROCESSFAKENAME &
	fi
    echo -n "starting $DESC... "
    screen -S backlog -d -m $EXEC
    echo "done."
    ;;
  *)
    echo "Usage: /etc/init.d/backlog {start|stop|restart}"
    ;;
esac
