# -*- coding: UTF-8 -*-
__author__      = "Tonio Gsell <tgsell@tik.ee.ethz.ch>"
__copyright__   = "Copyright 2010 ETH Zurich Switzerland Tonio Gsell"
__license__     = "GPL"
__version__     = "$Revision$"
__date__        = "$Date$"
__id__          = "$Id$"
__source__      = "$URL$"



'''
 The AM Msg Types
'''
AM_ALL = 'all'

AM_CONTROLCOMMAND = 0x21
AM_BEACONCOMMAND = 0x22

AM_DATANODEHEALTH = 0x80
AM_DATANODEINFO = 0x82
AM_DATAADCDIFF = 0x84
AM_DATADIGITALDCX = 0x86
AM_DATAADCMUX1 = 0x8A
AM_DATAADCMUX2 = 0x8C
AM_DATAWXT520WINDPTH = 0x92
AM_DATAWXT520PREC = 0x94
AM_DATAWXT520SUP = 0xA4
AM_DATAWXT520IDENT = 0xA6
AM_DATADECAGONMUX = 0xA0
AM_DOZERBASESTATUS = 0x88
AM_DOZERBASEDEBUG = 0x8E
AM_COMMANDMSG = 0x50
AM_DRIFT = 0x96 
AM_RSSI = 0x9a
AM_STATECOUNTER = 0x9e
AM_DOZEROBJECTSTATUS = 0x90


'''
 Dozer Beacon commands
'''
# Dozer Beacon Structure
DOZER_BEACON_STRUCTURE = [('destination', 'int', 2), ('cmd', 'int', 2), ('repetitionCnt','int',1)]

# The Commands
ACCESSNODE_QUEUE_CTRL_CMD = 8
ACCESSNODE_QUEUE_CTRL_CMD_VAL_CLOSE = 0
ACCESSNODE_QUEUE_CTRL_CMD_VAL_OPEN = 1
ACCESSNODE_QUEUE_CTRL_CMD_VAL_CLOSED = 2


'''
 BBv2PowerControl commands
'''
# Command Structure
CONTROL_CMD_STRUCTURE = [('command', 'int', 1), ('argument', 'int', 4)]

# The Commands to send
CONTROL_CMD_WAKEUP_QUERY = 1
CONTROL_CMD_SERVICE_WINDOW = 2
CONTROL_CMD_NEXT_WAKEUP = 3
CONTROL_CMD_SHUTDOWN = 4
CONTROL_CMD_NET_STATUS = 5
CONTROL_CMD_RESET_WATCHDOG = 6
CONTROL_CMD_WLAN_ON = 7
CONTROL_CMD_WLAN_OFF = 8

# The wakeup types
CONTROL_WAKEUP_TYPE_SCHEDULED = 1
CONTROL_WAKEUP_TYPE_SERVICE = 2
CONTROL_WAKEUP_TYPE_BEACON = 4
CONTROL_WAKEUP_TYPE_NODE_REBOOT = 8

