/* CVS $Id: $ */
package ch.epfl.gsn.vocab; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/ontology/ssn.owl 
 * @author Auto-generated by schemagen on 03 sept. 2014 17:58 
 */
public class Ssn {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.oclc.org/NET/ssnx/ssn#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property attachedSystem = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#attachedSystem" );
    
    public static final Property deployedOnPlatform = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#deployedOnPlatform" );
    
    public static final Property deployedSystem = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#deployedSystem" );
    
    public static final Property deploymentProcessPart = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#deploymentProcessPart" );
    
    public static final Property detects = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#detects" );
    
    public static final Property endTime = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#endTime" );
    
    public static final Property featureOfInterest = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#featureOfInterest" );
    
    public static final Property forProperty = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#forProperty" );
    
    public static final Property hasDeployment = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasDeployment" );
    
    public static final Property hasInput = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasInput" );
    
    public static final Property hasMeasurementCapability = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasMeasurementCapability" );
    
    public static final Property hasMeasurementProperty = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasMeasurementProperty" );
    
    public static final Property hasOperatingProperty = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasOperatingProperty" );
    
    public static final Property hasOperatingRange = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasOperatingRange" );
    
    public static final Property hasOutput = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasOutput" );
    
    public static final Property hasProperty = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasProperty" );
    
    public static final Property hasSubSystem = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasSubSystem" );
    
    public static final Property hasSurvivalProperty = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasSurvivalProperty" );
    
    public static final Property hasSurvivalRange = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasSurvivalRange" );
    
    public static final Property hasValue = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#hasValue" );
    
    public static final Property implementedBy = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#implementedBy" );
    
    public static final Property implements_ = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#implements" );
    
    public static final Property inCondition = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#inCondition" );
    
    public static final Property inDeployment = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#inDeployment" );
    
    public static final Property isProducedBy = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#isProducedBy" );
    
    public static final Property isPropertyOf = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#isPropertyOf" );
    
    public static final Property isProxyFor = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#isProxyFor" );
    
    public static final Property madeObservation = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#madeObservation" );
    
    public static final Property observationResult = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#observationResult" );
    
    public static final Property observationResultTime = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#observationResultTime" );
    
    public static final Property observationSamplingTime = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime" );
    
    public static final Property observedBy = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#observedBy" );
    
    public static final Property observedProperty = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#observedProperty" );
    
    public static final Property observes = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#observes" );
    
    public static final Property ofFeature = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#ofFeature" );
    
    public static final Property onPlatform = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#onPlatform" );
    
    public static final Property qualityOfObservation = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#qualityOfObservation" );
    
    public static final Property sensingMethodUsed = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#sensingMethodUsed" );
    
    public static final Property startTime = m_model.createProperty( "http://purl.oclc.org/NET/ssnx/ssn#startTime" );
    
    public static final Resource Accuracy = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Accuracy" );
    
    public static final Resource BatteryLifetime = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#BatteryLifetime" );
    
    public static final Resource Condition = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Condition" );
    
    public static final Resource Deployment = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Deployment" );
    
    public static final Resource DeploymentRelatedProcess = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#DeploymentRelatedProcess" );
    
    public static final Resource DetectionLimit = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#DetectionLimit" );
    
    public static final Resource Device = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Device" );
    
    public static final Resource Drift = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Drift" );
    
    public static final Resource FeatureOfInterest = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#FeatureOfInterest" );
    
    public static final Resource Frequency = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Frequency" );
    
    public static final Resource Input = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Input" );
    
    public static final Resource Latency = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Latency" );
    
    public static final Resource MaintenanceSchedule = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#MaintenanceSchedule" );
    
    public static final Resource MeasurementCapability = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#MeasurementCapability" );
    
    public static final Resource MeasurementProperty = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#MeasurementProperty" );
    
    public static final Resource MeasurementRange = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#MeasurementRange" );
    
    public static final Resource Observation = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Observation" );
    
    public static final Resource ObservationValue = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#ObservationValue" );
    
    public static final Resource OperatingPowerRange = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#OperatingPowerRange" );
    
    public static final Resource OperatingProperty = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#OperatingProperty" );
    
    public static final Resource OperatingRange = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#OperatingRange" );
    
    public static final Resource Output = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Output" );
    
    public static final Resource Platform = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Platform" );
    
    public static final Resource Precision = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Precision" );
    
    public static final Resource Process = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Process" );
    
    public static final Resource Property = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Property" );
    
    public static final Resource Resolution = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Resolution" );
    
    public static final Resource ResponseTime = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#ResponseTime" );
    
    public static final Resource Selectivity = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Selectivity" );
    
    public static final Resource Sensing = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Sensing" );
    
    public static final Resource SensingDevice = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SensingDevice" );
    
    public static final Resource Sensitivity = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Sensitivity" );
    
    public static final Resource Sensor = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Sensor" );
    
    public static final Resource SensorDataSheet = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SensorDataSheet" );
    
    public static final Resource SensorInput = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SensorInput" );
    
    public static final Resource SensorOutput = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SensorOutput" );
    
    public static final Resource Stimulus = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#Stimulus" );
    
    public static final Resource SurvivalProperty = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SurvivalProperty" );
    
    public static final Resource SurvivalRange = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SurvivalRange" );
    
    public static final Resource System = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#System" );
    
    public static final Resource SystemLifetime = m_model.createResource( "http://purl.oclc.org/NET/ssnx/ssn#SystemLifetime" );
    
}

/*
@footer@
*/

